//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.09 at 04:09:37 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://smorales.com/dto", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.smorales.dto;
